<a href="https://colab.research.google.com/github/hafizmuhammadyahya123/Data-Science/blob/main/datasci3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
products = ['A' , 'B' , 'C' , 'D' , 'E' , 'F']
products

['A', 'B', 'C', 'D', 'E', 'F']

In [ ]:
type(products)

list

In [ ]:
product_categories = pd.Series(products)
product_categories

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [ ]:
type(product_categories)

pandas.core.series.Series

In [ ]:
x = [3,4,5,6]
var = pd.Series(x , index = ['a','s','d','f'] , dtype = "float" , name="python")
print(var)


a    3.0
s    4.0
d    5.0
f    6.0
Name: python, dtype: float64


DATA FRAME

In [ ]:
pd.DataFrame(var)

python
a     3.0
s     4.0
d     5.0
f     6.0

In [ ]:
start_dates_deposite = pd.Series({
    '7/3/2000' : 3000,
    '3/5/2003' : 10000,
    '18/11/2024' : 8000,
    '25/7/2021' : 6000,
    '17/9/2018' : 90000,
    '25/8/2005' : 80000
})
start_dates_deposite

7/3/2000       3000
3/5/2003      10000
18/11/2024     8000
25/7/2021      6000
17/9/2018     90000
25/8/2005     80000
dtype: int64

In [ ]:
start_dates_deposite.sum()

197000

In [ ]:
start_dates_deposite.min()

3000

In [ ]:
start_dates_deposite.idxmin()

'7/3/2000'

In [ ]:
start_dates_deposite.idxmax()

'17/9/2018'

In [ ]:
start_dates_deposite.head()

7/3/2000       3000
3/5/2003      10000
18/11/2024     8000
25/7/2021      6000
17/9/2018     90000
dtype: int64

In [ ]:
start_dates_deposite.tail()

3/5/2003      10000
18/11/2024     8000
25/7/2021      6000
17/9/2018     90000
25/8/2005     80000
dtype: int64

DATAFRAME

In [ ]:
import pandas as pd
import numpy as np
arry_1 = np.array([[3,2,1],[1,6,2]])
arry_1

array([[3, 2, 1],
       [1, 6, 2]])

In [ ]:
pd.DataFrame(arry_1)

0  1  2
0  3  2  1
1  1  6  2

In [ ]:
type(pd.DataFrame(arry_1))

pandas.core.frame.DataFrame

In [ ]:
df = pd.DataFrame(arry_1, columns = ['column 1' , 'column 2' , 'column 3'])
df

column 1  column 2  column 3
0         3         2         1
1         1         6         2

In [ ]:
df = pd.DataFrame(arry_1 , columns = ['column 1', 'column 2' , 'column 3'])
df

column 1  column 2  column 3
0         3         2         1
1         1         6         2

In [ ]:
ary = np.array([[10,20,30,40,50],[3,15,25,35,45]])
ary

pd.DataFrame(ary)

dfrm = pd.DataFrame(ary,columns=['C1','C2','C3','C4','C5'],index = ['R1','R2'])
dfrm

C1  C2  C3  C4  C5
R1  10  20  30  40  50
R2   3  15  25  35  45

In [ ]:
dict_A = {
    'name' : ['AHSAN','ALI','SAAD','FAROOQ'],
    'marks' : [98,50,30,70],
    'city' : ['karachi','sawat','gilgit','islamabad']

}

In [ ]:
df = pd.DataFrame(dict_A)

In [ ]:
df

name  marks       city
0   AHSAN     98    karachi
1     ALI     50      sawat
2    SAAD     30     gilgit
3  FAROOQ     70  islamabad

.to_CSV

In [ ]:
import pandas as pd
dis = {
    'a':[1,2,3,4,5,6],'b':[1,2,3,4,5,6],'c':[1,2,3,4,5,6]
}

d = pd.DataFrame(dis)

print(d)
d.to_csv("My_Data3.csv",index=False,header=[1,2,3])

   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6


In [ ]:
d.values

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [ ]:
d.columns

Index(['a', 'b', 'c'], dtype='object')

.read_csv

In [ ]:
path = "/content/sample_data/california_housing_test.csv"
Data = pd.read_csv(path)
sample_data_califo = Data.copy()
sample_data_califo.head(20)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0     -122.05     37.37                27.0       3885.0           661.0   
1     -118.30     34.26                43.0       1510.0           310.0   
2     -117.81     33.78                27.0       3589.0           507.0   
3     -118.36     33.82                28.0         67.0            15.0   
4     -119.67     36.33                19.0       1241.0           244.0   
5     -119.56     36.51                37.0       1018.0           213.0   
6     -121.43     38.63                43.0       1009.0           225.0   
7     -120.65     35.48                19.0       2310.0           471.0   
8     -122.84     38.40                15.0       3080.0           617.0   
9     -118.02     34.08                31.0       2402.0           632.0   
10    -118.24     33.98                45.0        972.0           249.0   
11    -119.12     35.85                37.0        736.0           166.0   
12    -121.93     37.25                36.0       1089.0           182.0   
13    -117.03     32.97                16.0       3936.0           694.0   
14    -117.97     33.73                27.0       2097.0           325.0   
15    -117.99     33.81                42.0        161.0            40.0   
16    -120.81     37.53                15.0        570.0           123.0   
17    -121.20     38.69                26.0       3077.0           607.0   
18    -118.88     34.21                26.0       1590.0           196.0   
19    -122.59     38.01                35.0       8814.0          1307.0   

    population  households  median_income  median_house_value  
0       1537.0       606.0         6.6085            344700.0  
1        809.0       277.0         3.5990            176500.0  
2       1484.0       495.0         5.7934            270500.0  
3         49.0        11.0         6.1359            330000.0  
4        850.0       237.0         2.9375             81700.0  
5        663.0       204.0         1.6635             67000.0  
6        604.0       218.0         1.6641             67000.0  
7       1341.0       441.0         3.2250            166900.0  
8       1446.0       599.0         3.6696            194400.0  
9       2830.0       603.0         2.3333            164200.0  
10      1288.0       261.0         2.2054            125000.0  
11       564.0       138.0         2.4167             58300.0  
12       535.0       170.0         4.6900            252600.0  
13      1935.0       659.0         4.5625            231200.0  
14      1217.0       331.0         5.7121            222500.0  
15       157.0        50.0         2.2000            153100.0  
16       189.0       107.0         1.8750            181300.0  
17      1603.0       595.0         2.7174            137500.0  
18       654.0       199.0         6.5851            300000.0  
19      3450.0      1258.0         6.1724            414300.0

In [ ]:
type(sample_data_califo.columns)

pandas.core.indexes.base.Index

In [ ]:
type(sample_data_califo.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
sample_data_califo.values # values fn DataFrameconvert to numpy

array([[-1.22050e+02,  3.73700e+01,  2.70000e+01, ...,  6.06000e+02,
         6.60850e+00,  3.44700e+05],
       [-1.18300e+02,  3.42600e+01,  4.30000e+01, ...,  2.77000e+02,
         3.59900e+00,  1.76500e+05],
       [-1.17810e+02,  3.37800e+01,  2.70000e+01, ...,  4.95000e+02,
         5.79340e+00,  2.70500e+05],
       ...,
       [-1.19700e+02,  3.63000e+01,  1.00000e+01, ...,  2.20000e+02,
         2.28950e+00,  6.20000e+04],
       [-1.17120e+02,  3.41000e+01,  4.00000e+01, ...,  1.40000e+01,
         3.27080e+00,  1.62500e+05],
       [-1.19630e+02,  3.44200e+01,  4.20000e+01, ...,  2.60000e+02,
         8.56080e+00,  5.00001e+05]])

In [ ]:
sample_data_califo.values.shape

(3000, 9)

.read_csv

In [ ]:
Data = pd.read_csv("/content/sample_data/california_housing_test.csv")
sample_data_califo = Data
sample_data_califo.head(20)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0     -122.05     37.37                27.0       3885.0           661.0   
1     -118.30     34.26                43.0       1510.0           310.0   
2     -117.81     33.78                27.0       3589.0           507.0   
3     -118.36     33.82                28.0         67.0            15.0   
4     -119.67     36.33                19.0       1241.0           244.0   
5     -119.56     36.51                37.0       1018.0           213.0   
6     -121.43     38.63                43.0       1009.0           225.0   
7     -120.65     35.48                19.0       2310.0           471.0   
8     -122.84     38.40                15.0       3080.0           617.0   
9     -118.02     34.08                31.0       2402.0           632.0   
10    -118.24     33.98                45.0        972.0           249.0   
11    -119.12     35.85                37.0        736.0           166.0   
12    -121.93     37.25                36.0       1089.0           182.0   
13    -117.03     32.97                16.0       3936.0           694.0   
14    -117.97     33.73                27.0       2097.0           325.0   
15    -117.99     33.81                42.0        161.0            40.0   
16    -120.81     37.53                15.0        570.0           123.0   
17    -121.20     38.69                26.0       3077.0           607.0   
18    -118.88     34.21                26.0       1590.0           196.0   
19    -122.59     38.01                35.0       8814.0          1307.0   

    population  households  median_income  median_house_value  
0       1537.0       606.0         6.6085            344700.0  
1        809.0       277.0         3.5990            176500.0  
2       1484.0       495.0         5.7934            270500.0  
3         49.0        11.0         6.1359            330000.0  
4        850.0       237.0         2.9375             81700.0  
5        663.0       204.0         1.6635             67000.0  
6        604.0       218.0         1.6641             67000.0  
7       1341.0       441.0         3.2250            166900.0  
8       1446.0       599.0         3.6696            194400.0  
9       2830.0       603.0         2.3333            164200.0  
10      1288.0       261.0         2.2054            125000.0  
11       564.0       138.0         2.4167             58300.0  
12       535.0       170.0         4.6900            252600.0  
13      1935.0       659.0         4.5625            231200.0  
14      1217.0       331.0         5.7121            222500.0  
15       157.0        50.0         2.2000            153100.0  
16       189.0       107.0         1.8750            181300.0  
17      1603.0       595.0         2.7174            137500.0  
18       654.0       199.0         6.5851            300000.0  
19      3450.0      1258.0         6.1724            414300.0

In [ ]:
sample_data_califo.index

RangeIndex(start=0, stop=3000, step=1)

In [ ]:
type(sample_data_califo.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
type(sample_data_califo.dtypes)

pandas.core.series.Series

.read_csv

In [ ]:
Data_1 = pd.read_csv("My_Data.csv")
s = Data_1
s.head(5)

Unnamed: 0  a  b  c
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5

In [ ]:
s.values #values fn DataFrame convert to numpy

array([[0, 1, 1, 1],
       [1, 2, 2, 2],
       [2, 3, 3, 3],
       [3, 4, 4, 4],
       [4, 5, 5, 5],
       [5, 6, 6, 6]])

In [ ]:
s.values.shape

(6, 4)

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
s.columns

Index(['Unnamed: 0', 'a', 'b', 'c'], dtype='object')

In [ ]:
len(s.columns)

4

In [ ]:
type(s.columns)

pandas.core.indexes.base.Index

In [ ]:
type(s.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
type(s.dtypes)

pandas.core.series.Series

In [ ]:
s.to_numpy #similar work .values

<bound method DataFrame.to_numpy of    Unnamed: 0  a  b  c
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6>

In [ ]:
Data = pd.read_csv("/content/sample_data/california_housing_test.csv",index_col="longitude") #langitude series index ki placees pr use hogi
sample_data_califo = Data
sample_data_califo.head(20)

latitude  housing_median_age  total_rooms  total_bedrooms  \
longitude                                                              
-122.05       37.37                27.0       3885.0           661.0   
-118.30       34.26                43.0       1510.0           310.0   
-117.81       33.78                27.0       3589.0           507.0   
-118.36       33.82                28.0         67.0            15.0   
-119.67       36.33                19.0       1241.0           244.0   
-119.56       36.51                37.0       1018.0           213.0   
-121.43       38.63                43.0       1009.0           225.0   
-120.65       35.48                19.0       2310.0           471.0   
-122.84       38.40                15.0       3080.0           617.0   
-118.02       34.08                31.0       2402.0           632.0   
-118.24       33.98                45.0        972.0           249.0   
-119.12       35.85                37.0        736.0           166.0   
-121.93       37.25                36.0       1089.0           182.0   
-117.03       32.97                16.0       3936.0           694.0   
-117.97       33.73                27.0       2097.0           325.0   
-117.99       33.81                42.0        161.0            40.0   
-120.81       37.53                15.0        570.0           123.0   
-121.20       38.69                26.0       3077.0           607.0   
-118.88       34.21                26.0       1590.0           196.0   
-122.59       38.01                35.0       8814.0          1307.0   

           population  households  median_income  median_house_value  
longitude                                                             
-122.05        1537.0       606.0         6.6085            344700.0  
-118.30         809.0       277.0         3.5990            176500.0  
-117.81        1484.0       495.0         5.7934            270500.0  
-118.36          49.0        11.0         6.1359            330000.0  
-119.67         850.0       237.0         2.9375             81700.0  
-119.56         663.0       204.0         1.6635             67000.0  
-121.43         604.0       218.0         1.6641             67000.0  
-120.65        1341.0       441.0         3.2250            166900.0  
-122.84        1446.0       599.0         3.6696            194400.0  
-118.02        2830.0       603.0         2.3333            164200.0  
-118.24        1288.0       261.0         2.2054            125000.0  
-119.12         564.0       138.0         2.4167             58300.0  
-121.93         535.0       170.0         4.6900            252600.0  
-117.03        1935.0       659.0         4.5625            231200.0  
-117.97        1217.0       331.0         5.7121            222500.0  
-117.99         157.0        50.0         2.2000            153100.0  
-120.81         189.0       107.0         1.8750            181300.0  
-121.20        1603.0       595.0         2.7174            137500.0  
-118.88         654.0       199.0         6.5851            300000.0  
-122.59        3450.0      1258.0         6.1724            414300.0

In [ ]:
sample_data_califo.housing_median_age #particular column print = var.column

longitude
-122.05    27.0
-118.30    43.0
-117.81    27.0
-118.36    28.0
-119.67    19.0
           ... 
-119.86    23.0
-118.14    27.0
-119.70    10.0
-117.12    40.0
-119.63    42.0
Name: housing_median_age, Length: 3000, dtype: float64

In [ ]:
sample_data_califo.population #particular column print = var.column

longitude
-122.05    1537.0
-118.30     809.0
-117.81    1484.0
-118.36      49.0
-119.67     850.0
            ...  
-119.86    1258.0
-118.14    3496.0
-119.70     693.0
-117.12      46.0
-119.63     753.0
Name: population, Length: 3000, dtype: float64

In [ ]:
# this method much better way as compare from above
sample_data_califo['population'] #particular column print = var['column'] column name as a str pss

longitude
-122.05    1537.0
-118.30     809.0
-117.81    1484.0
-118.36      49.0
-119.67     850.0
            ...  
-119.86    1258.0
-118.14    3496.0
-119.70     693.0
-117.12      46.0
-119.63     753.0
Name: population, Length: 3000, dtype: float64

In [ ]:
# var[index main ['list pss wo bhi str form main']]
sample_data_califo[['total_bedrooms','population']] #particular column print = var[['column','volumn2,...]]

total_bedrooms  population
longitude                            
-122.05             661.0      1537.0
-118.30             310.0       809.0
-117.81             507.0      1484.0
-118.36              15.0        49.0
-119.67             244.0       850.0
...                   ...         ...
-119.86             642.0      1258.0
-118.14            1082.0      3496.0
-119.70             201.0       693.0
-117.12              14.0        46.0
-119.63             263.0       753.0

[3000 rows x 2 columns]

In [ ]:
sample_data_califo[['households','total_rooms']].head()  #head() first five rows pss

households  total_rooms
longitude                         
-122.05         606.0       3885.0
-118.30         277.0       1510.0
-117.81         495.0       3589.0
-118.36          11.0         67.0
-119.67         237.0       1241.0

In [ ]:
sample_data_califo.iloc[1] # column name ko rows main aik saath show krwata ha this fn = using rows

latitude                  34.260
housing_median_age        43.000
total_rooms             1510.000
total_bedrooms           310.000
population               809.000
households               277.000
median_income              3.599
median_house_value    176500.000
Name: -118.3, dtype: float64

In [ ]:
sample_data_califo.iloc[1,3] #1st Row & 3rd Column

310.0

In [ ]:
sample_data_califo.iloc[:,3] # ab complete column index3 pss hoga

longitude
-122.05     661.0
-118.30     310.0
-117.81     507.0
-118.36      15.0
-119.67     244.0
            ...  
-119.86     642.0
-118.14    1082.0
-119.70     201.0
-117.12      14.0
-119.63     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
sample_data_califo.iloc[4:10,:]

latitude  housing_median_age  total_rooms  total_bedrooms  \
longitude                                                              
-119.67       36.33                19.0       1241.0           244.0   
-119.56       36.51                37.0       1018.0           213.0   
-121.43       38.63                43.0       1009.0           225.0   
-120.65       35.48                19.0       2310.0           471.0   
-122.84       38.40                15.0       3080.0           617.0   
-118.02       34.08                31.0       2402.0           632.0   

           population  households  median_income  median_house_value  
longitude                                                             
-119.67         850.0       237.0         2.9375             81700.0  
-119.56         663.0       204.0         1.6635             67000.0  
-121.43         604.0       218.0         1.6641             67000.0  
-120.65        1341.0       441.0         3.2250            166900.0  
-122.84        1446.0       599.0         3.6696            194400.0  
-118.02        2830.0       603.0         2.3333            164200.0

In [ ]:
sample_data_califo.loc[:,'total_bedrooms']

longitude
-122.05     661.0
-118.30     310.0
-117.81     507.0
-118.36      15.0
-119.67     244.0
            ...  
-119.86     642.0
-118.14    1082.0
-119.70     201.0
-117.12      14.0
-119.63     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
import numpy as np
ary_x = np.array([1,2,3,4,5])
ary_x

array([1, 2, 3, 4, 5])

In [ ]:
for i in ary_x:
  print(i)

1
2
3
4
5


In [ ]:
for idx , ele in ary_x:  #yahan error mily ga
  print(idx,ele)

In [ ]:
for idx,ele in enumerate(ary_x): #index ko print krwany k liya or same process list,tuple,numpy arry pr bhi use ho skta ha
  print(idx,ele)

0 1
1 2
2 3
3 4
4 5


In [ ]:
import pandas as pd
lst = ["A","B","C","D","E"]
lst


['A', 'B', 'C', 'D', 'E']

In [ ]:
pro = pd.Series(lst)
pro

0    A
1    B
2    C
3    D
4    E
dtype: object

In [ ]:
lst1 = [10,20,30,40,50]
lst1

[10, 20, 30, 40, 50]

In [ ]:
pro1=pd.Series(lst1) #Series S is Capital
pro1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
lst2 = ["A",0,1.2,"B",True,(1,2,3,4)]
lst2

['A', 0, 1.2, 'B', True, (1, 2, 3, 4)]

In [ ]:
type(lst2)

list

In [ ]:
pro2 = pd.Series(lst2)
pro2

0               A
1               0
2             1.2
3               B
4            True
5    (1, 2, 3, 4)
dtype: object

In [ ]:
type(pro2)

pandas.core.series.Series

In [ ]:
lstX = {

    "LIST1":[2,4,5,7,9,1],
    "LIST2":["two","four","five","seven","nine","one"],
    "LIST3":["two=3","four=4","five=4","seven=5","nine=4","one=3"],
    "LIST4":['2=3','4=4','5=4','7=5','9=4','1=3']
}

pro3 = pd.Series(lstX,name="pandas")
pro3

LIST1                                 [2, 4, 5, 7, 9, 1]
LIST2                [two, four, five, seven, nine, one]
LIST3    [two=3, four=4, five=4, seven=5, nine=4, one=3]
LIST4                     [2=3, 4=4, 5=4, 7=5, 9=4, 1=3]
Name: pandas, dtype: object

In [ ]:
lstX = {

    "LIST1":2,
    "LIST2":"two",
    "LIST3":"two!=3" # "LIST4":'2!=3'
}
lstX

{'LIST1': 2, 'LIST2': 'two', 'LIST3': 'two!=3'}

In [ ]:
pro3 = pd.Series(lstX,)
pro3

LIST1         2
LIST2       two
LIST3    two!=3
dtype: object

In [ ]:

pro3 = pd.Series(lstX,index=["LIST1"],name="pandas") #index=['list str form']
pro3

LIST1    2
Name: pandas, dtype: object

In [ ]:
type(pro3)

pandas.core.series.Series

In [ ]:
print(pro3)

LIST1    2
Name: pandas, dtype: object


In [ ]:
pd.DataFrame(pro3)

pandas
LIST1      2

In [ ]:
pro3.min

<bound method Series.min of LIST1    2
Name: pandas, dtype: object>

In [ ]:
vari = pd.Series({
    "apple":5,
    "BANANA":6,
    "cherry":"six"
})
vari

apple       5
BANANA      6
cherry    six
dtype: object

In [ ]:
pd.Series(vari,name="fruits")

apple       5
BANANA      6
cherry    six
Name: fruits, dtype: object

In [ ]:
pd.DataFrame(vari)

0
apple     5
BANANA    6
cherry  six

In [ ]:
import numpy as np
aray = np.array([1,2,3,4,5])
aray

array([1, 2, 3, 4, 5])

In [ ]:
pd.Series(aray,index=['A','B','C','D','E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [ ]:
pd.DataFrame(aray,dtype="float",index=['row1','row2','row3','row4','row5'])

0
row1  1.0
row2  2.0
row3  3.0
row4  4.0
row5  5.0

In [ ]:
aray.min()

1

In [ ]:
aray.max()

5

In [ ]:
l = pd.Series([100,200,300,400,500,600,700,800],index=[50,100,150,200,250,300,350,400],name="python pandas")
l

50     100
100    200
150    300
200    400
250    500
300    600
350    700
400    800
Name: python pandas, dtype: int64

In [ ]:
pd.DataFrame(l)

column
50      100
100     200
150     300
200     400
250     500
300     600
350     700
400     800

In [ ]:
l.min() #column smallest value pss

100

In [ ]:
l.max() #column biggest value pss

800

In [ ]:
l.idxmax()

400

In [ ]:
l.idxmin()

50

In [ ]:
l.head() #first 5 rows pass

50     100
100    200
150    300
200    400
250    500
Name: column, dtype: int64

In [ ]:
l.tail() #last 5 rows pss

200    400
250    500
300    600
350    700
400    800
Name: column, dtype: int64

In [ ]:
type(l)

pandas.core.series.Series

In [ ]:
pd.DataFrame(arr)

0  1  2  3  4
0  w  r  o  s  t
1  k  i  n  g  s

In [ ]:
_arry = np.array(['c','a','t'])
_arry

array(['c', 'a', 't'], dtype='<U1')

In [ ]:
pd.Series(_arry,index=['t','a','c'],name="pandas")

t    c
a    a
c    t
Name: pandas, dtype: object

In [ ]:
pd.DataFrame(_arry,index=['a','c','t'],columns=['column'])

column
a      c
c      a
t      t

In [ ]:
type(_arry)

numpy.ndarray

In [ ]:
_arry.shape

(3,)

In [ ]:
_arry.size

3

In [ ]:
_ar1=np.array([[1,9,2,8,3],[4,6,7,10,12]])
_ar1

array([[ 1,  9,  2,  8,  3],
       [ 4,  6,  7, 10, 12]])

In [ ]:
_ar1.shape

(2, 5)

In [ ]:
pd.DataFrame(_ar1,columns=['c0','c1','c2','c3','c4'],index=['r0','r1'])

c0  c1  c2  c3  c4
r0   1   9   2   8   3
r1   4   6   7  10  12

In [ ]:
_ar1.size

10

In [ ]:
_ar1.shape

(2, 5)

In [ ]:
var_dic=pd.Series({
    "information":"sec",
    "cyber":"sec",
    "network":"sec"

},index=['cyber'],name='PDDATA')
var_dic



cyber    sec
Name: PDDATA, dtype: object

In [ ]:
pd.DataFrame(var_dic,index=["information","cyber","network"])

PDDATA
information    NaN
cyber          sec
network        NaN

In [ ]:
type(var_dic)

pandas.core.series.Series

In [ ]:
var_dic.size

1

In [ ]:
var_dic.shape

(1,)

In [ ]:
var_diction = pd.Series([{
    "information":"sec",
    "cyber":"sec",
    "network":"sec"
}],index=["Row"],name="PD-DATA")

var_diction

Row    {'information': 'sec', 'cyber': 'sec', 'networ...
Name: PD-DATA, dtype: object

In [ ]:
pd.DataFrame(var_diction)

PD-DATA
Row  {'information': 'sec', 'cyber': 'sec', 'networ...

In [ ]:
type(var_diction)

pandas.core.series.Series

In [ ]:
var_diction.size

1

In [ ]:
var_diction.shape

(1,)

In [ ]:
var_d=pd.Series({
    "information":"sec",
    "cyber":"sec",
    "network":"sec"

},name="pypandas")
var_d

information    sec
cyber          sec
network        sec
Name: pypandas, dtype: object

In [ ]:
pd.DataFrame(var_d)

pypandas
information      sec
cyber            sec
network          sec

In [ ]:
var_d.size

3

In [ ]:
var_d.shape

(3,)

In [ ]:
import pandas as pd
import numpy as np
lst_1 = np.array([[1,2,3,7,'A','B','C','D'],[4,5,6,8,'E','F','G','H']])
lst_1

array([['1', '2', '3', '7', 'A', 'B', 'C', 'D'],
       ['4', '5', '6', '8', 'E', 'F', 'G', 'H']], dtype='<U21')

In [ ]:
pd.DataFrame(lst_1,index=['ROW0','ROW1'],columns=['column0','column1','column2','column3','column4','column5','column6','column7'])

column0 column1 column2 column3 column4 column5 column6 column7
ROW0       1       2       3       7       A       B       C       D
ROW1       4       5       6       8       E       F       G       H

In [ ]:
type(lst_1)

numpy.ndarray

In [ ]:
diction_A = {
    'country':['AMERICA','CANADA','SYRIA','RUSSIA','LONDON','AUTRALIA','JAPAN'],
    'year':[2002,2009,2010,2012,2019,2020,2022],
    'rank':['A','B','C','D','E','F','G']
}
print(diction_A)

pd.DataFrame(diction_A,index=['ROW1','ROW2','ROW3','ROW4','ROW5','ROW6','ROW7'])

{'country': ['AMERICA', 'CANADA', 'SYRIA', 'RUSSIA', 'LONDON', 'AUTRALIA', 'JAPAN'], 'year': [2002, 2009, 2010, 2012, 2019, 2020, 2022], 'rank': ['A', 'B', 'C', 'D', 'E', 'F', 'G']}


country  year rank
ROW1   AMERICA  2002    A
ROW2    CANADA  2009    B
ROW3     SYRIA  2010    C
ROW4    RUSSIA  2012    D
ROW5    LONDON  2019    E
ROW6  AUTRALIA  2020    F
ROW7     JAPAN  2022    G

In [ ]:
pd.Series(diction_A)

country    [AMERICA, CANADA, SYRIA, RUSSIA, LONDON, AUTRA...
year              [2002, 2009, 2010, 2012, 2019, 2020, 2022]
rank                                   [A, B, C, D, E, F, G]
dtype: object

In [ ]:
import pandas as pd
dic = {
    'r':[1,2,4,5,7,8,10],
    's':[3,12,13,15,16,18,20],
    't':[21,22,23,24,25,26,27]
}
pd.Series(dic)

r          [1, 2, 4, 5, 7, 8, 10]
s     [3, 12, 13, 15, 16, 18, 20]
t    [21, 22, 23, 24, 25, 26, 27]
dtype: object

In [ ]:
pd.DataFrame(dic)

r   s   t
0   1   3  21
1   2  12  22
2   4  13  23
3   5  15  24
4   7  16  25
5   8  18  26
6  10  20  27

In [ ]:
pd.DataFrame(dic,index=['R1','R2','R3','R4','R5','R6','R7'],columns=['c1','c2','c3'])

c1   c2   c3
R1  NaN  NaN  NaN
R2  NaN  NaN  NaN
R3  NaN  NaN  NaN
R4  NaN  NaN  NaN
R5  NaN  NaN  NaN
R6  NaN  NaN  NaN
R7  NaN  NaN  NaN

In [ ]:
pd.DataFrame(dic,columns=['r','s','t'])

r   s   t
0   1   3  21
1   2  12  22
2   4  13  23
3   5  15  24
4   7  16  25
5   8  18  26
6  10  20  27

In [ ]:
pd.DataFrame(dic,columns=['s'],index=['r1','r2','r3','r4','r5','r6','r7'])

s
r1   3
r2  12
r3  13
r4  15
r5  16
r6  18
r7  20

In [ ]:
pd.DataFrame(dic)

r   s   t
0   1   3  21
1   2  12  22
2   4  13  23
3   5  15  24
4   7  16  25
5   8  18  26
6  10  20  27

In [ ]:
import pandas as pd
dict_ionary = {
    'population_year':[1945,1999,2000,2003,2005,2010,2020],
    'monkey':[5000,10000,8000,13000,15000,4000,20000],
    'lion':[20000,19000,15000,21000,14000,10000,8000],
    'tiger':[10000,4000,8000,13000,15000,4000,20000],
    'deer':[5000,10000,8000,13000,15000,4000,20000],
    'big cat':[20000,19000,15000,21000,14000,10000,8000],
    'zebra':[10000,4000,8000,13000,15000,4000,20000],
    'eagle':[5000,10000,8000,13000,15000,4000,20000],
    'parrot':[20000,19000,15000,21000,14000,10000,8000],
    'cheetah':[10000,4000,8000,13000,15000,4000,20000],
    'black panther':[5000,10000,8000,13000,15000,4000,20000],
    'wolf':[20000,19000,15000,21000,14000,10000,8000],
    'dove':[10000,4000,8000,13000,15000,4000,20000],
    'horse':[10000,4000,8000,13000,15000,4000,20000],
    'sparrow':[5000,10000,8000,13000,15000,4000,20000],
    'fisher':[20000,19000,15000,21000,14000,10000,8000],
    'budgies':[10000,4000,8000,13000,15000,4000,20000],
    'black move':[5000,10000,8000,13000,15000,4000,20000],
    'bear':[20000,19000,15000,21000,14000,10000,8000],
    'panda':[10000,4000,8000,13000,15000,4000,20000]

}
pd.Series(dict_ionary,name='WILD_LIFE')




population_year          [1945, 1999, 2000, 2003, 2005, 2010, 2020]
monkey               [5000, 10000, 8000, 13000, 15000, 4000, 20000]
lion               [20000, 19000, 15000, 21000, 14000, 10000, 8000]
tiger                [10000, 4000, 8000, 13000, 15000, 4000, 20000]
deer                 [5000, 10000, 8000, 13000, 15000, 4000, 20000]
big cat            [20000, 19000, 15000, 21000, 14000, 10000, 8000]
zebra                [10000, 4000, 8000, 13000, 15000, 4000, 20000]
eagle                [5000, 10000, 8000, 13000, 15000, 4000, 20000]
parrot             [20000, 19000, 15000, 21000, 14000, 10000, 8000]
cheetah              [10000, 4000, 8000, 13000, 15000, 4000, 20000]
black panther        [5000, 10000, 8000, 13000, 15000, 4000, 20000]
wolf               [20000, 19000, 15000, 21000, 14000, 10000, 8000]
dove                 [10000, 4000, 8000, 13000, 15000, 4000, 20000]
horse                [10000, 4000, 8000, 13000, 15000, 4000, 20000]
sparrow              [5000, 10000, 8000, 13000, 15000, 4000, 20000]
fisher             [20000, 19000, 15000, 21000, 14000, 10000, 8000]
budgies              [10000, 4000, 8000, 13000, 15000, 4000, 20000]
black move           [5000, 10000, 8000, 13000, 15000, 4000, 20000]
bear               [20000, 19000, 15000, 21000, 14000, 10000, 8000]
panda                [10000, 4000, 8000, 13000, 15000, 4000, 20000]
Name: WILD_LIFE, dtype: object

In [ ]:
pd.DataFrame(dict_ionary,index=['ind0','ind1','ind2','ind3','ind4','ind5','ind6'])

population_year  monkey   lion  tiger   deer  big cat  zebra  eagle  \
ind0             1945    5000  20000  10000   5000    20000  10000   5000   
ind1             1999   10000  19000   4000  10000    19000   4000  10000   
ind2             2000    8000  15000   8000   8000    15000   8000   8000   
ind3             2003   13000  21000  13000  13000    21000  13000  13000   
ind4             2005   15000  14000  15000  15000    14000  15000  15000   
ind5             2010    4000  10000   4000   4000    10000   4000   4000   
ind6             2020   20000   8000  20000  20000     8000  20000  20000   

      parrot  cheetah  black panther   wolf   dove  horse  sparrow  fisher  \
ind0   20000    10000           5000  20000  10000  10000     5000   20000   
ind1   19000     4000          10000  19000   4000   4000    10000   19000   
ind2   15000     8000           8000  15000   8000   8000     8000   15000   
ind3   21000    13000          13000  21000  13000  13000    13000   21000   
ind4   14000    15000          15000  14000  15000  15000    15000   14000   
ind5   10000     4000           4000  10000   4000   4000     4000   10000   
ind6    8000    20000          20000   8000  20000  20000    20000    8000   

      budgies  black move   bear  panda  
ind0    10000        5000  20000  10000  
ind1     4000       10000  19000   4000  
ind2     8000        8000  15000   8000  
ind3    13000       13000  21000  13000  
ind4    15000       15000  14000  15000  
ind5     4000        4000  10000   4000  
ind6    20000       20000   8000  20000

In [ ]:
dict_ionary = {
    'population_year':[1945,1999,2000,2003,2005,2010,2020],
    'monkey':[5000,10000,8000,13000,15000,4000,20000],
    'lion':[20000,19000,15000,21000,14000,10000,8000],
    'tiger':[10000,4000,8000,13000,15000,4000,20000],
    'deer':[5000,10000,8000,13000,15000,4000,20000],
    'big cat':[20000,19000,15000,21000,14000,10000,8000],
    'zebra':[10000,4000,8000,13000,15000,4000,20000],
    'eagle':[5000,10000,8000,13000,15000,4000,20000],
    'parrot':[20000,19000,15000,21000,14000,10000,8000],
    'cheetah':[10000,4000,8000,13000,15000,4000,20000],
    'black panther':[5000,10000,8000,13000,15000,4000,20000],
    'wolf':[20000,19000,15000,21000,14000,10000,8000],
    'dove':[10000,4000,8000,13000,15000,4000,20000],
    'horse':[10000,4000,8000,13000,15000,4000,20000],
    'sparrow':[5000,10000,8000,13000,15000,4000,20000],
    'fisher':[20000,19000,15000,21000,14000,10000,8000],
    'budgies':[10000,4000,8000,13000,15000,4000,20000],
    'black move':[5000,10000,8000,13000,15000,4000,20000],
    'bear':[20000,19000,15000,21000,14000,10000,8000],
    'panda':[10000,4000,8000,13000,15000,4000,20000]

}
dta=pd.DataFrame(dict_ionary)
print(dta)

dta.to_csv('animal_data_set.csv')

   population_year  monkey   lion  tiger   deer  big cat  zebra  eagle  \
0             1945    5000  20000  10000   5000    20000  10000   5000   
1             1999   10000  19000   4000  10000    19000   4000  10000   
2             2000    8000  15000   8000   8000    15000   8000   8000   
3             2003   13000  21000  13000  13000    21000  13000  13000   
4             2005   15000  14000  15000  15000    14000  15000  15000   
5             2010    4000  10000   4000   4000    10000   4000   4000   
6             2020   20000   8000  20000  20000     8000  20000  20000   

   parrot  cheetah  black panther   wolf   dove  horse  sparrow  fisher  \
0   20000    10000           5000  20000  10000  10000     5000   20000   
1   19000     4000          10000  19000   4000   4000    10000   19000   
2   15000     8000           8000  15000   8000   8000     8000   15000   
3   21000    13000          13000  21000  13000  13000    13000   21000   
4   14000    15000          1500

In [ ]:
dta.values  #VALUES fn = DataFrame convert to array

array([[ 1945,  5000, 20000, 10000,  5000, 20000, 10000,  5000, 20000,
        10000,  5000, 20000, 10000, 10000,  5000, 20000, 10000,  5000,
        20000, 10000],
       [ 1999, 10000, 19000,  4000, 10000, 19000,  4000, 10000, 19000,
         4000, 10000, 19000,  4000,  4000, 10000, 19000,  4000, 10000,
        19000,  4000],
       [ 2000,  8000, 15000,  8000,  8000, 15000,  8000,  8000, 15000,
         8000,  8000, 15000,  8000,  8000,  8000, 15000,  8000,  8000,
        15000,  8000],
       [ 2003, 13000, 21000, 13000, 13000, 21000, 13000, 13000, 21000,
        13000, 13000, 21000, 13000, 13000, 13000, 21000, 13000, 13000,
        21000, 13000],
       [ 2005, 15000, 14000, 15000, 15000, 14000, 15000, 15000, 14000,
        15000, 15000, 14000, 15000, 15000, 15000, 14000, 15000, 15000,
        14000, 15000],
       [ 2010,  4000, 10000,  4000,  4000, 10000,  4000,  4000, 10000,
         4000,  4000, 10000,  4000,  4000,  4000, 10000,  4000,  4000,
        10000,  4000],
       [ 2

In [ ]:
dta.columns

Index(['population_year', 'monkey', 'lion', 'tiger', 'deer', 'big cat',
       'zebra', 'eagle', 'parrot', 'cheetah', 'black panther', 'wolf', 'dove',
       'horse', 'sparrow', 'fisher', 'budgies', 'black move', 'bear', 'panda'],
      dtype='object')

In [ ]:
path_A = pd.read_csv('/content/My_Data3.csv')
sample_d = path_A
sample_d.head(2)


1  2  3
0  1  1  1
1  2  2  2

In [ ]:
import pandas as pd
pth = "/content/sample_data/mnist_test.csv"
d = pd.read_csv(pth)
d

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [ ]:
d.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

In [ ]:
d.head(3)

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  

[3 rows x 785 columns]

In [ ]:
d.values

array([[2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0]])

In [ ]:
d.values.shape

(9999, 785)

In [ ]:
type(d)

pandas.core.frame.DataFrame

In [ ]:
type(d.columns)

pandas.core.indexes.base.Index

In [ ]:
type(d.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
len(d.index)

9999

In [ ]:
len(d.columns)

785

In [ ]:
pth_2 = "/content/sample_data/california_housing_train.csv"
d2 = pd.read_csv(pth_2,index_col='longitude')
d2


latitude  housing_median_age  total_rooms  total_bedrooms  \
longitude                                                              
-114.31       34.19                15.0       5612.0          1283.0   
-114.47       34.40                19.0       7650.0          1901.0   
-114.56       33.69                17.0        720.0           174.0   
-114.57       33.64                14.0       1501.0           337.0   
-114.57       33.57                20.0       1454.0           326.0   
...             ...                 ...          ...             ...   
-124.26       40.58                52.0       2217.0           394.0   
-124.27       40.69                36.0       2349.0           528.0   
-124.30       41.84                17.0       2677.0           531.0   
-124.30       41.80                19.0       2672.0           552.0   
-124.35       40.54                52.0       1820.0           300.0   

           population  households  median_income  median_house_value  
longitude                                                             
-114.31        1015.0       472.0         1.4936             66900.0  
-114.47        1129.0       463.0         1.8200             80100.0  
-114.56         333.0       117.0         1.6509             85700.0  
-114.57         515.0       226.0         3.1917             73400.0  
-114.57         624.0       262.0         1.9250             65500.0  
...               ...         ...            ...                 ...  
-124.26         907.0       369.0         2.3571            111400.0  
-124.27        1194.0       465.0         2.5179             79000.0  
-124.30        1244.0       456.0         3.0313            103600.0  
-124.30        1298.0       478.0         1.9797             85800.0  
-124.35         806.0       270.0         3.0147             94600.0  

[17000 rows x 8 columns]

In [ ]:
d2[['total_rooms','households']].head()

total_rooms  households
longitude                         
-114.31         5612.0       472.0
-114.47         7650.0       463.0
-114.56          720.0       117.0
-114.57         1501.0       226.0
-114.57         1454.0       262.0

In [ ]:
d2[['households','total_bedrooms']].tail()

households  total_bedrooms
longitude                            
-124.26         369.0           394.0
-124.27         465.0           528.0
-124.30         456.0           531.0
-124.30         478.0           552.0
-124.35         270.0           300.0