<a href="https://colab.research.google.com/github/hafizmuhammadyahya123/Data-Science/blob/main/datasci2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY


In [ ]:
import numpy as np
x = np.arange(16)  #1D ARRAY
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
x.size

16

In [ ]:
x.shape

(16,)

In [ ]:
x2 = np.arange(10) #1D
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x2.size

10

In [ ]:
x2.shape

(10,)

In [ ]:
x3 = np.arange(20) #1D
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x.size

16

In [ ]:
x.shape

(16,)

In [ ]:
x4 = np.array([[1,2,3,4],[5,7,9,11]]) #2D
x4

array([[ 1,  2,  3,  4],
       [ 5,  7,  9, 11]])

In [ ]:
x4.size

8

In [ ]:
x4.shape

(2, 4)

In [ ]:
x5 = np.array(['a','b','c','d','d']) #1D
x5

array(['a', 'b', 'c', 'd', 'd'], dtype='<U1')

In [ ]:
x5.size

5

In [ ]:
type(x5)

numpy.ndarray

In [ ]:
x5.shape

(5,)

In [ ]:
x6 = np.array({"a":1,"b":2,"c":3})
x6

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [ ]:
type(x6)

numpy.ndarray

In [ ]:
x6.size

1

In [ ]:
x6.shape

()

In [ ]:
x1 = x.reshape(4 , 4)  #2D ARRAY
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
x3 = x.reshape(2 , 2 , 4)  #3D ARRAY
x3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
x = np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
x1 = x.reshape(5 , 5)
x1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
x1.max(axis=0) #max(axis=0) means every column always highest num print

array([20, 21, 22, 23, 24])

In [ ]:
x1.max(axis=1) #max(axis=1) means every row always highest num print

array([ 4,  9, 14, 19, 24])

In [ ]:
arr = np.arange(16).reshape(4,4) #2D ARRAY
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr1 = np.arange(36).reshape(2 , 3 , 6) #3D
arr1

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:
array2 = np.arange(64).reshape(2 , 4 , 8)
array2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [ ]:
z = np.zeros(( 4 , 4)) #zero k case main argument ko tuple form main pss kren gy
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z.ndim

2

In [ ]:
one = np.ones((4 , 4)) #one k case main argument ko tuple form main pss kren gy
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
emp = np.empty((4 , 4)) #empty main kuch na kuch value mily gi khali nahi hoga or isy tuple ya list main argument pss
emp

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 2D
emp1 = np.empty((2 , 4 , 2)) #empty argument pss tuple
emp1

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# 2D
emp1 = np.empty([2 , 4 , 2]) #empty() argument always tuple ya list main pss
emp1

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
ary = np.full([2,3], [44])
ary

array([[44, 44, 44],
       [44, 44, 44]])

In [ ]:
ary1 = np.full([4,4], (100))
ary1

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
ary2 = np.full([2,3,6], (50)) #3D
ary2

array([[[50, 50, 50, 50, 50, 50],
        [50, 50, 50, 50, 50, 50],
        [50, 50, 50, 50, 50, 50]],

       [[50, 50, 50, 50, 50, 50],
        [50, 50, 50, 50, 50, 50],
        [50, 50, 50, 50, 50, 50]]])

In [ ]:
ary3 = np.full([2,3,2], (12))
ary3

array([[[12, 12],
        [12, 12],
        [12, 12]],

       [[12, 12],
        [12, 12],
        [12, 12]]])

In [ ]:
lst = [200 , "PYTHON" , "learn" , 3.43]
np.array(lst)

array(['200', 'PYTHON', 'learn', '3.43'], dtype='<U32')

In [ ]:
a = np.arange(6,12,1).reshape(2,3)
a

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b = np.arange(6,12,1).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a*b   #broadcasting el vice mult

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
a-b  #broadcasting element vice min

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a+b  #broadcasting el vice plus

array([[12, 14, 16],
       [18, 20, 22]])

In [ ]:
a/b  #broadcasting el vice division

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a > b

array([[False, False, False],
       [False, False, False]])

In [ ]:
a < b

array([[False, False, False],
       [False, False, False]])

In [ ]:
a != b

array([[False, False, False],
       [False, False, False]])

In [ ]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a >= b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a <= b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a[a%3 == 1]

array([ 7, 10])

In [ ]:
import numpy as np
values = np.random.randn(3,3)
values

array([[-1.00638233,  0.53643604,  0.49345576],
       [-0.52208508,  0.88602392,  0.56801648],
       [ 0.55324706,  0.57188663,  0.33813982]])

In [ ]:
data = np.array([['cat','dog','cat'],['cat','dog','dog'],['dog','cat','cat']])
data

array([['cat', 'dog', 'cat'],
       ['cat', 'dog', 'dog'],
       ['dog', 'cat', 'cat']], dtype='<U3')

In [ ]:
values[data == 'cat']

array([-1.00638233,  0.49345576, -0.52208508,  0.57188663,  0.33813982])

In [ ]:
values[data == 'dog']

array([0.53643604, 0.88602392, 0.56801648, 0.55324706])

In [ ]:
values[data == 'cat''dog']

array([], dtype=float64)

In [ ]:
arr = np.random.randn(10 , 10)
print(arr)
print(np.round(arr,2))

[[-0.39511691 -0.37817271 -1.58976171  0.34055659  0.96626358 -0.45926358
  -0.86775816 -1.6847488  -0.71019008 -0.99768772]
 [-1.67492638 -0.41955302  0.86393134  0.1253725  -0.47740687  1.17113711
  -2.36598654  1.69093752  0.16025362 -0.99789939]
 [-0.64770011  1.08514127 -1.52860176  0.36976566 -0.12153131  1.47037793
   0.88743561 -0.77066945  0.17906358 -0.91328547]
 [ 0.53515165  0.02392972 -0.46500901  1.74362345 -0.68319144  2.10422416
   0.91767051  0.70287831 -1.57920626  0.997031  ]
 [ 0.6064264   0.77382181  1.14994156 -0.04459313 -1.40565781 -0.28093848
   0.48798618  0.4638307  -0.19941441 -0.50269984]
 [ 1.18008685  1.22538678 -0.21766334  0.51386594  0.53917568  0.28875436
  -1.87397346  0.40356489  0.64835943 -0.2860654 ]
 [ 0.2686963   0.54354001 -0.29890769 -0.46957989  0.9139975   2.03002884
  -0.86563024 -2.10342293  0.39286323 -0.05993957]
 [-0.42981742 -0.47063315 -0.25909379 -1.17851827  0.1399868  -0.273989
   0.65174783 -1.44501535 -1.54668905  0.17332785]
 [

In [ ]:
arr = np.random.randn(10 , 10)
print(arr)
arr1 = np.round(arr,2)
print(arr1)

[[ 0.43580694 -0.10537659 -0.44422467  0.96683178  0.54071932  2.39099211
  -0.48388538  0.91960704 -2.26235564  0.34228957]
 [ 1.36512223  1.26977622 -0.98669006 -2.55060836 -0.4758607   0.32234382
  -1.22402342  1.11302844  2.16543255 -0.52066333]
 [-0.98262977 -0.97580613 -0.45824699  1.4193253  -1.38941129 -2.21344131
   0.56757185  0.61089341 -0.51454076 -0.94805756]
 [ 1.84038826 -0.89970008 -1.11693103 -0.97390011 -0.64381088 -1.30798005
  -0.92700912  1.57439126 -0.35114741 -0.2316251 ]
 [-1.41781067 -1.29653342  0.25011214 -1.18701644  0.5385614   2.00982853
   0.27344621  0.26978945  0.38266076  1.38164931]
 [-0.61754026 -0.27424175  0.18693866  1.51216684  0.40157924  0.09134443
   0.39796078 -1.84824239  0.45425107 -0.68730726]
 [-1.16731558 -0.82103557 -0.11207577  0.1867054  -0.01336859 -1.10155879
   1.20741105  1.2398828   1.30373563  0.7286437 ]
 [ 0.17565277 -0.64003793  1.22402674 -1.13447482  1.08380296  0.50625208
   0.55998694  0.42219646  0.71467832  1.48495162]


In [ ]:
print(arr1[1:10:2])

[[ 1.37  1.27 -0.99 -2.55 -0.48  0.32 -1.22  1.11  2.17 -0.52]
 [ 1.84 -0.9  -1.12 -0.97 -0.64 -1.31 -0.93  1.57 -0.35 -0.23]
 [-0.62 -0.27  0.19  1.51  0.4   0.09  0.4  -1.85  0.45 -0.69]
 [ 0.18 -0.64  1.22 -1.13  1.08  0.51  0.56  0.42  0.71  1.48]
 [ 1.31 -0.7  -0.47 -0.46 -0.6  -0.48 -0.54 -0.17 -0.03  1.34]]


In [ ]:
print(arr1[1:10:2,::])

[[ 1.37  1.27 -0.99 -2.55 -0.48  0.32 -1.22  1.11  2.17 -0.52]
 [ 1.84 -0.9  -1.12 -0.97 -0.64 -1.31 -0.93  1.57 -0.35 -0.23]
 [-0.62 -0.27  0.19  1.51  0.4   0.09  0.4  -1.85  0.45 -0.69]
 [ 0.18 -0.64  1.22 -1.13  1.08  0.51  0.56  0.42  0.71  1.48]
 [ 1.31 -0.7  -0.47 -0.46 -0.6  -0.48 -0.54 -0.17 -0.03  1.34]]


In [ ]:
print(arr1[::,0:4]) #all rows & 1st four columns print

[[ 0.44 -0.11 -0.44  0.97]
 [ 1.37  1.27 -0.99 -2.55]
 [-0.98 -0.98 -0.46  1.42]
 [ 1.84 -0.9  -1.12 -0.97]
 [-1.42 -1.3   0.25 -1.19]
 [-0.62 -0.27  0.19  1.51]
 [-1.17 -0.82 -0.11  0.19]
 [ 0.18 -0.64  1.22 -1.13]
 [ 0.95  1.06 -0.38 -0.63]
 [ 1.31 -0.7  -0.47 -0.46]]


In [ ]:
x = np.array([0 , 1 , 2 , 3 , 4])
y = np.array([2 , 4 , 6 , 8 , 10])
np.maximum(x , y)

array([ 2,  4,  6,  8, 10])

In [ ]:
import numpy as np
var = np.array([10,20,30,40,50])
var1 = np.array([5,10,20,40,60])
np.maximum(var,var1)

array([10, 20, 30, 40, 60])

In [ ]:
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)
y = np.arange(6).reshape(3,2)
print(y)
# x * y  yahan error mily ga q k array shape or range differ ha

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)
y = np.arange(9).reshape(3,3)
print(y)
x*y

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

AGAIN PRACTICE....


In [ ]:
a = np.arange(24) #1D
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.size

24

In [ ]:
a.shape

(24,)

In [ ]:
b = np.array([1,2,3,4,5]) #1D
b

array([1, 2, 3, 4, 5])

In [ ]:
b.size

5

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(5,)

In [ ]:
c = np.array([['a','b','c','d'],['e','f','g','h']]) #2D
c

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h']], dtype='<U1')

In [ ]:
c.size

8

In [ ]:
c.shape

(2, 4)

In [ ]:
d = np.array([[2.2,3.3,4.4],[5.5,6.6,7.7]])
d

array([[2.2, 3.3, 4.4],
       [5.5, 6.6, 7.7]])

In [ ]:
d.size

6

In [ ]:
e = np.array([{"t":2,"f":4,"s":6}])
print(e)

[{'t': 2, 'f': 4, 's': 6}]


In [ ]:
e.size

1

In [ ]:
e.shape

(1,)

In [ ]:
f = np.array({
    "fish":1,
    "banana":2,
    "egg":3,
    "arm":"strog"
})
print(f)

{'fish': 1, 'banana': 2, 'egg': 3, 'arm': 'strog'}


In [ ]:
type(f)

numpy.ndarray

In [ ]:
f.size

1

In [ ]:
f.shape

()

In [ ]:
g = np.array({
    "fruits":["apple","banane","orange","cherry"],
    "sea_foods":["fish","categA","categB","cateC"],
    "sweet_dish":["halwa","jalebi","rabdi","cake"]
})
print(g)

{'fruits': ['apple', 'banane', 'orange', 'cherry'], 'sea_foods': ['fish', 'categA', 'categB', 'cateC'], 'sweet_dish': ['halwa', 'jalebi', 'rabdi', 'cake']}


In [ ]:
g.size

1

In [ ]:
g.shape

(1,)

In [ ]:
g = np.array([{
    "fruits":("apple","banane","orange","cherry"),
    "sea_foods":("fish","categA","categB","cateC"),
    "sweet_dish":("halwa","jalebi","rabdi","cake")
}])
print(g)

[{'fruits': ('apple', 'banane', 'orange', 'cherry'), 'sea_foods': ('fish', 'categA', 'categB', 'cateC'), 'sweet_dish': ('halwa', 'jalebi', 'rabdi', 'cake')}]


In [ ]:
g.size

1

In [ ]:
g.shape

(1,)

In [ ]:
h = np.array({"a":"apple","b":"banana","c":"cake"})
print(h)

{'a': 'apple', 'b': 'banana', 'c': 'cake'}


In [ ]:
h.size

1

In [ ]:
h.shape

()

In [ ]:
i = np.array(["a","b","c"])
print(i)

['a' 'b' 'c']


In [ ]:
i.size

3

In [ ]:
i.shape

(3,)

In [ ]:
a = np.arange(24) #1D
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.reshape(3,8) #1D convert TO 2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a.reshape(2,2,6)  #1D convert TO 3D

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
a.reshape(6,2,2) #3D


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [ ]:
arr = np.arange(3**2).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
ay = np.arange(3**2).reshape(3,3)
ay

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr+ay


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr-ay

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr/ay

<ipython-input-119-95069d8e3bb4>:1: RuntimeWarning: invalid value encountered in divide
  arr/ay


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [ ]:
ary=arr%ay
ary
arr=ary+2
arr**0

<ipython-input-129-7137f0b69067>:1: RuntimeWarning: divide by zero encountered in remainder
  ary=arr%ay


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr = np.array([{"arr**0":"unity"}])
arr

array([{'arr**0': 'unity'}], dtype=object)

In [ ]:
arr.shape

(1,)

In [ ]:
arr.size

1