<a href="https://colab.research.google.com/github/hafizmuhammadyahya123/Data-Science/blob/main/datasci2_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# 1D ARRAY list from array
list = [1,2,3,4,5,6]
np_array = np.array(list,)
np_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 1D ARRAY using arange()
arange_fn = np.arange(20,31)
arange_fn

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# 2D ARRAY using reshape()
reshape_fn = arange_fn.reshape(11,1)
reshape_fn

array([[20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30]])

In [ ]:
# 2D ARRAY list from array
list_int = [[20,30,40,50,60],[70,80,90,100,110]]
np_array = np.array(list_int,dtype=float)
np_array

array([[ 20.,  30.,  40.,  50.,  60.],
       [ 70.,  80.,  90., 100., 110.]])

In [ ]:
# 2D ARRAY using arange().reshape()
np_array_arange_reshape = np.arange(2,11).reshape(3,3)
np_array_arange_reshape

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np_array_arange_reshape.shape


(3, 3)

In [ ]:
np_array_arange_reshape.size

9

In [ ]:
# 2D  using list
import numpy as np
float_list = [[2.1,2.4,2.9,3.1,9.9],[2.1,2.2,9.8,1.1,2.3]]
np_array = np.array(float_list)
np_array

array([[2.1, 2.4, 2.9, 3.1, 9.9],
       [2.1, 2.2, 9.8, 1.1, 2.3]])

In [ ]:
type(np_array)

numpy.ndarray

In [ ]:
np_array = np.array(np_array,'U32')
np_array

array([['2.1', '2.4', '2.9', '3.1', '9.9'],
       ['2.1', '2.2', '9.8', '1.1', '2.3']], dtype='<U32')

In [ ]:
# 3D
array_range = np.arange(100,200,1).reshape(5,10,2)
array_range

array([[[100, 101],
        [102, 103],
        [104, 105],
        [106, 107],
        [108, 109],
        [110, 111],
        [112, 113],
        [114, 115],
        [116, 117],
        [118, 119]],

       [[120, 121],
        [122, 123],
        [124, 125],
        [126, 127],
        [128, 129],
        [130, 131],
        [132, 133],
        [134, 135],
        [136, 137],
        [138, 139]],

       [[140, 141],
        [142, 143],
        [144, 145],
        [146, 147],
        [148, 149],
        [150, 151],
        [152, 153],
        [154, 155],
        [156, 157],
        [158, 159]],

       [[160, 161],
        [162, 163],
        [164, 165],
        [166, 167],
        [168, 169],
        [170, 171],
        [172, 173],
        [174, 175],
        [176, 177],
        [178, 179]],

       [[180, 181],
        [182, 183],
        [184, 185],
        [186, 187],
        [188, 189],
        [190, 191],
        [192, 193],
        [194, 195],
        [196, 197],
        [198

In [ ]:
# 3D
array_range = np.arange(100,200,3).reshape(17,2)
array_range

array([[100, 103],
       [106, 109],
       [112, 115],
       [118, 121],
       [124, 127],
       [130, 133],
       [136, 139],
       [142, 145],
       [148, 151],
       [154, 157],
       [160, 163],
       [166, 169],
       [172, 175],
       [178, 181],
       [184, 187],
       [190, 193],
       [196, 199]])